### ISSUE TITLE
How to build go?

### ISSUE THREAD

**Issue by testinfected** [facebook/buck2#455]
Hi, I'm trying to use the example go toolchain, but it seems out of date.

Apparently it does not include some require values for `GoToolChainInfo`, namely `compiler_flags_shared`,  `compiler_flags_static`,  `linker_flags_shared`,  `linker_flags_static` as well as `prebuilt_stdlib` and `prebuilt_stdlib_shared`.

I tried filling out those values, but don't know what to provide for `prebuilt_stdlib`. With an empty map I get the following error:

`Error running analysis for `root//... (prelude//platforms:default#524f8da68ea2a374)`

Caused by:
    Traceback (most recent call last):
      File <builtin>, in <module>
      * prelude/go/go_library.bzl:40, in go_library_impl
          static_pkg = compile(
      * prelude/go/compile.bzl:148, in compile
          cmd.add(cmd_args(_compile_cmd(ctx, pkg_name, pkgs, deps, compile_flags, share...
      * prelude/go/compile.bzl:110, in _compile_cmd
          stdlib_pkg_artifacts(go_toolchain, shared = shared),
    error: Type of parameters mismatch, expected `int`, actual `provider_callable`
      --> prelude/go/packages.bzl:56:19
       |
    56 |     stdlib_pkgs = prebuilt_stdlib[ArtifactGroupInfo].artifacts
       |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
`

Is there an example of a working Go Toolchain somewhere?

Any help would be appreciated. 

Thanks

**Comment by testinfected** [comment]
Should I understand nobody is using Buck2 to build go?

**Comment by ndmitchell** [comment]
We are using Buck2 internally to build Go. But we don't have any open source samples. That's kind of the weird middle ground - you can probably get it working, but it will require a bit of work. I'll see if anyone internally can be persuaded to shed some light (I know the build system, but not much about how Go works with it).

**Comment by podtserkovskiy** [comment]
Hey @testinfected, 

I can share some context on buck2&Go integration, we are using it internally for limited purposes.

This is in active development at the moment. We will make some breaking changes time to time to make it better.
So, at this moment we can't give any promise of API compatibility. 

However I can answer some of your questions.

> compiler_flags_shared, compiler_flags_static, linker_flags_shared, linker_flags_static

Just leave them empty for the beginning.

> don't know what to provide for prebuilt_stdlib

You need to pre-build it manually using following command
```
export GODEBUG="installgoroot=all"
shared_flags="-gcflags -shared -asmflags -shared"
go install -pkgdir "$out_dir/prebuilt_std/static" std
go install -pkgdir "$out_dir/prebuilt_std/shared" $shared_flags std
```

Then wrap into into filegroups
```
    filegroup(
        name = "stdlib_static",
        srcs = native.glob(["prebuilt_std/static/**/*"]),
    )

    filegroup(
        name = "stdlib_shared",
        srcs = native.glob(["prebuilt_std/shared/**/*"]),
    )
```

And then supply it into `GoToolChainInfo`. I suppose you are using go_toolchain for it 😀

**Comment by sluongng** [comment]
That’s close to what we do in Bazel’s rules_go https://github.com/bazelbuild/rules_go/blob/2f29bd3956a37156f0dee39b761109a490f0a47b/go/tools/builders/stdlib.go#L115

Note that would would probably want to filter out `go install` generated `buildid` as it could make your build not reproducible.

**Comment by testinfected** [comment]
Thanks, will try that. I'm very new to Buck, so fingers crossed

**Comment by dvtkrlbs** [comment]
@podtserkovskiy hey what should be the param for gen_stdlib_importcfg should be. I am trying to make https://github.com/sluongng/buck2-go work with the current 
version of buck2. and currently getting an error like this

<details>
<summary>shell output</summary>

```sh
Running action: anon//:http_archive@f05825da4029d31f (http_archive) (build), local executor: env -- 'TMPDIR=/Users/dvtkrlbs/DEV/safarifruits/geomys/buck-out/v2/tmp-anon/anon/6c0c0ee7f897af38f05825da4029d31f/__http_archive__/http_archive' 'BUCK_SCRATCH_PATH=buck-out/v2/tmp-anon/anon/6c0c0ee7f897af38f05825da4029d31f/__http_archive__/http_archive' 'BUCK2_DAEMON_UUID=407d0906-13c3-4401-b87a-c2c64e02a357' 'BUCK_BUILD_ID=55f10eed-5e07-408a-934c-520e98d71512' /bin/sh buck-out/v2/gen-anon/anon/6c0c0ee7f897af38f05825da4029d31f/__http_archive__/unpack.sh
Running action: prelude//go/tools:stdlib (prelude//platforms:default#6c0c0ee7f897af38) (go_build_stdlib go_build_stdlib) (build), local executor: env -- 'TMPDIR=/Users/dvtkrlbs/DEV/safarifruits/geomys/buck-out/v2/tmp/prelude/6c0c0ee7f897af38/go/tools/__stdlib__/go_build_stdlib/go_build_stdlib' 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/prelude/6c0c0ee7f897af38/go/tools/__stdlib__/go_build_stdlib/go_build_stdlib' 'BUCK2_DAEMON_UUID=407d0906-13c3-4401-b87a-c2c64e02a357' 'BUCK_BUILD_ID=55f10eed-5e07-408a-934c-520e98d71512' env 'GOEXPERIMENT=nocoverageredesign' 'GOARCH=arm64' 'GOOS=darwin' 'GOROOT=buck-out/v2/gen-anon/anon/6c0c0ee7f897af38f05825da4029d31f/__http_archive__/http_archive' 'CGO_ENABLED=1' 'GODEBUG=installgoroot=all' 'CGO_ENABLED=0' '' buck-out/v2/gen-anon/anon/6c0c0ee7f897af38f05825da4029d31f/__http_archive__/http_archive/bin/go install -pkgdir buck-out/v2/gen/prelude/6c0c0ee7f897af38/go/tools/__stdlib__/stdlib_pkgdir '-gcflags=-buildid=' std
Running action: root//:example (prelude//platforms:default#6c0c0ee7f897af38) (go_filter_srcs) (build), local executor: env -- 'TMPDIR=/Users/dvtkrlbs/DEV/safarifruits/geomys/buck-out/v2/tmp/root/6c0c0ee7f897af38/__example__/go_filter_srcs' 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/root/6c0c0ee7f897af38/__example__/go_filter_srcs' 'BUCK2_DAEMON_UUID=407d0906-13c3-4401-b87a-c2c64e02a357' 'BUCK_BUILD_ID=55f10eed-5e07-408a-934c-520e98d71512' env 'GOEXPERIMENT=nocoverageredesign' 'GOARCH=arm64' 'GOOS=darwin' 'GOROOT=buck-out/v2/gen-anon/anon/6c0c0ee7f897af38f05825da4029d31f/__http_archive__/http_archive' 'CGO_ENABLED=1' /usr/bin/env 'PYTHONPATH=buck-out/v2/gen/prelude/6c0c0ee7f897af38/go/tools/__filter_srcs__/__filter_srcs__' python3 buck-out/v2/gen/prelude/6c0c0ee7f897af38/go/tools/__filter_srcs__/filter_srcs.py '--go=buck-out/v2/gen-anon/anon/6c0c0ee7f897af38f05825da4029d31f/__http_archive__/http_archive/bin/go' '--tags=' '--output=buck-out/v2/gen/root/6c0c0ee7f897af38/__example__/__filtered_srcs__.txt' buck-out/v2/gen/root/6c0c0ee7f897af38/__example__/__srcs__
Action failed: prelude//go/tools:stdlib (go_build_stdlib go_build_stdlib)
Local command returned non-zero exit code 127
Reproduce locally: `env -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/prelude/6c0c0ee7f897af38/go/tools/__stdlib__/go_build_stdlib/go_build_stdlib' env 'GOEXPERIMENT=nocoverageredesign' 'GOARCH=arm64' 'GOOS=darwin' 'GOROOT=buck-out/v2/gen-anon/anon/6c0c0ee7f897af38f05825da4029d31f/__http_archive__/http_archive' 'CGO_ENABLED=1' 'GODEBUG=installgoroot=all' 'CGO_ENABLED=0' '' buck-out/v2/gen-anon/anon/6c0c0ee7f897af38f05825da4029d31f/__http_archive__/http_archive/bin/go install -pkgdir buck-out/v2/gen/prelude/6c0c0ee7f897af38/go/tools/__stdlib__/stdlib_pkgdir '-gcflags=-buildid=' std`
stdout:
stderr:
env: : No such file or directory
Build ID: 55f10eed-5e07-408a-934c-520e98d71512

```
</details>

here is my patch of the prelude to make some NoneType errors disappear

<details>
<summary>patch</summary>

```
diff --git a/go/go_stdlib.bzl b/go/go_stdlib.bzl
index 49414dc7..88eea2d6 100644
--- a/go/go_stdlib.bzl
+++ b/go/go_stdlib.bzl
@@ -39,10 +39,11 @@ def go_stdlib_impl(ctx: AnalysisContext) -> list[Provider]:
         ]
 
     cmd = get_toolchain_cmd_args(go_toolchain, go_root = True)
+    print(go_toolchain.go_wrapper)
     cmd.add([
         "GODEBUG={}".format("installgoroot=all"),
         "CGO_ENABLED={}".format("1" if cgo_enabled else "0"),
-        go_toolchain.go_wrapper,
+        go_toolchain.go_wrapper if go_toolchain.go_wrapper else "",
         go_toolchain.go,
         go_wrapper_args,
         "install",
@@ -59,9 +60,10 @@ def go_stdlib_impl(ctx: AnalysisContext) -> list[Provider]:
     ctx.actions.run(cmd, category = "go_build_stdlib", identifier = "go_build_stdlib")
 
     importcfg = ctx.actions.declare_output("stdlib.importcfg")
+    print(importcfg.as_output())
     ctx.actions.run(
         [
-            go_toolchain.gen_stdlib_importcfg,
+            go_toolchain.gen_stdlib_importcfg if go_toolchain.gen_stdlib_importcfg else "",
             "--stdlib",
             stdlib_pkgdir,
             "--output",
diff --git a/go/packages.bzl b/go/packages.bzl
index 6ca43871..8133ed91 100644
--- a/go/packages.bzl
+++ b/go/packages.bzl
@@ -92,7 +92,7 @@ def make_importcfg(
     final_importcfg = ctx.actions.declare_output(root, "{}.final.importcfg".format(pkg_name))
     ctx.actions.run(
         [
-            go_toolchain.concat_files,
+            go_toolchain.concat_files if go_toolchain.concat_files else "",
             "--output",
             final_importcfg.as_output(),
             stdlib.importcfg,
diff --git a/toolchains/go.bzl b/toolchains/go.bzl
index 2201a2c2..8a829ea8 100644
--- a/toolchains/go.bzl
+++ b/toolchains/go.bzl
@@ -6,7 +6,7 @@ load("@prelude//os_lookup:defs.bzl", "OsLookup")
 load("@prelude//:prelude.bzl", "native")
 load(":go_toolchain_release.bzl", "GO_SDKS_METADATA")
 
-def _get_go_arch() -> "string":
+def _get_go_arch():
     arch = host_info().arch
     if arch.is_aarch64:
         return "arm64"
@@ -15,7 +15,7 @@ def _get_go_arch() -> "string":
     else:
         fail("Unsupported go arch: {}".format(arch))
 
-def _get_go_os() -> "string":
+def _get_go_os():
     os = host_info().os
     if os.is_macos:
         return "darwin"
@@ -24,10 +24,10 @@ def _get_go_os() -> "string":
     else:
         fail("Unsupported go os: {}".format(os))
 
-def _go_tool_path(go_os: "string", go_arch: "string", go_tool: "string") -> "string":
+def _go_tool_path(go_os, go_arch, go_tool):
     return "pkg/tool/{}_{}/{}".format(go_os, go_arch, go_tool)
 
-def _system_go_toolchain_impl(ctx: "context") -> ["provider"]:
+def _system_go_toolchain_impl(ctx):
     exec_os = ctx.attrs._exec_os_type[OsLookup]
     go_arch = "amd64" if exec_os.cpu == "x86_64" else exec_os.cpu
     go_os = exec_os.platform
@@ -47,9 +47,9 @@ def _system_go_toolchain_impl(ctx: "context") -> ["provider"]:
         GoToolchainInfo(
             # Go binary
             go = go_binary,
-            sdk_srcs = srcs,
-            sdk_headers = headers,
-            sdk_tools = tools,
+            #sdk_srcs = srcs,
+            #sdk_headers = headers,
+            #sdk_tools = tools,
             # Go env
             env_go_arch = go_arch,
             env_go_os = go_os,
@@ -57,11 +57,9 @@ def _system_go_toolchain_impl(ctx: "context") -> ["provider"]:
             env_go_arm = None,
             # Go tools
             compiler = get_go_tool("compile"),
-            compiler_flags_shared = "",
-            compiler_flags_static = "",
+            compiler_flags = "",
             linker = get_go_tool("link"),
-            linker_flags_shared = "",
-            linker_flags_static = "",
+            linker_flags = "",
             assembler = get_go_tool("asm"),
             cover = get_go_tool("cover"),
             packer = get_go_tool("pack"),
@@ -100,10 +98,13 @@ system_go_toolchain = rule(
     is_toolchain_rule = True,
 )
 
-def _remote_go_toolchain_impl(ctx) -> ["promise", ["provider"]]:
+def _remote_go_toolchain_impl(ctx):
     exec_os = ctx.attrs._exec_os_type[OsLookup]
     go_arch = "amd64" if exec_os.cpu == "x86_64" else exec_os.cpu
-    go_os = exec_os.platform
+    go_os = "darwin" if exec_os.platform == "macos" else exec_os.platform
+    print(exec_os)
+    print(go_arch)
+    print(go_os)
 
     expected_version = "go" + ctx.attrs.version
     sdk_metadata = None
@@ -122,7 +123,7 @@ def _remote_go_toolchain_impl(ctx) -> ["promise", ["provider"]]:
     if not sdk_file_metadata:
         fail("Could not find suitable download ({}, {}) for go version: {}".format(go_os, go_arch, ctx.attrs.version))
 
-    def handle_toolchain_archive(providers: "provider_collection") -> ["provider"]:
+    def handle_toolchain_archive(providers):
         go_root = providers[DefaultInfo].default_outputs[0]
         archive_sub_targets = providers[DefaultInfo].sub_targets
 
@@ -140,9 +141,9 @@ def _remote_go_toolchain_impl(ctx) -> ["promise", ["provider"]]:
             GoToolchainInfo(
                 # Go binary
                 go = go_binary,
-                sdk_srcs = srcs,
-                sdk_headers = headers,
-                sdk_tools = tools,
+                #sdk_srcs = srcs,
+                #sdk_headers = headers,
+                #sdk_tools = tools,
                 # Go env
                 env_go_arch = go_arch,
                 env_go_os = go_os,
@@ -150,12 +151,11 @@ def _remote_go_toolchain_impl(ctx) -> ["promise", ["provider"]]:
                 env_go_arm = None,
                 # Go tools
                 compiler = get_go_tool("compile"),
-                compiler_flags_shared = "",
-                compiler_flags_static = "",
+                compiler_flags = [],
                 linker = get_go_tool("link"),
-                linker_flags_shared = "",
-                linker_flags_static = "",
+                linker_flags = [],
                 assembler = get_go_tool("asm"),
+                assembler_flags = [],
                 cover = get_go_tool("cover"),
                 packer = get_go_tool("pack"),
                 # Helpers
@@ -188,7 +188,7 @@ def _remote_go_toolchain_impl(ctx) -> ["promise", ["provider"]]:
             ]
         ] + ["bin/go", "pkg/include", "pkg/tool", "src"],
         "strip_prefix": "go",
-    }).map(handle_toolchain_archive)
+    }).promise.map(handle_toolchain_archive)
 
 remote_go_toolchain = rule(
     impl = _remote_go_toolchain_impl,
diff --git a/toolchains/go_toolchain_release.bzl b/toolchains/go_toolchain_release.bzl
index 06dde730..05a2b14c 100644
--- a/toolchains/go_toolchain_release.bzl
+++ b/toolchains/go_toolchain_release.bzl
@@ -1,36695 +1,45062 @@
 GO_SDKS_METADATA = [
+ # basically the output of https://go.dev/dl/?mode=json&include=all
+                   ]

```

</details>

**Comment by dvtkrlbs** [comment]
nvm i figured it out. apparently some of the tools like go_wrapper and gen_stdlib_import_cfg were not included in the attrs declaration. defining them made the issue go away. Will open a PR about this. another question I have is if I open a PR with remote go toolchain downloading implemented would this be approved if not I will just contribute the simple fixes I did

**Comment by podtserkovskiy** [comment]
I'm sorry for the late reply. Thanks for dong this work.

I removed need to pre-compile stdlibs, so now it should be easier.
I've just fixed some inconsistencies  we had in `GoToolchainInfo` attributes and now #577 is ready for merge and will be merged shortly.

**Comment by podtserkovskiy** [comment]
> if I open a PR with remote go toolchain downloading implemented would this be approved 

Let's double check with @ndmitchell and @JakobDegen, but personally I'm happy to approve

**Comment by JakobDegen** [comment]
I don't think we'd just approve it, I honestly think that more generally useful toolchain rules across languages is one of the highest value contributions buck2 could see right now. So yes, please do!

**Comment by podtserkovskiy** [comment]
BTW, I'm working on making `system_go_toolchain` work with go binary from PATH. 
Also, I'm adding some examples which will be compiled on CI and prevent breaking the system toolchain in the future.

I've just noticed we have some examples of downloading Go toolchain in `no_prelude` directory. You can use it together with `system_go_toolchain` for the inspiration 😀

**Comment by podtserkovskiy** [comment]
@dvtkrlbs @testinfected I've merged #588. So, `system_go_toolchain` works on Linux and MacOS, has an example of usage in `examples/with_prelude/go/hello` and those examples being validated on CI.

**Comment by testinfected** [comment]
Great news @podtserkovskiy ! Kudos

**Comment by dankox** [comment]
This issue is a bit old and the `system_go_toolchain` was published, but I'm curious how this can be used to do cross compilation of the Go binary. 

I was trying to create toolchain similar to `system_go_toolchain` where I hardcoded `env_go_os` and `env_go_arch`, but I still need to provide stdlib which is compiled for that platform (it's using the default one which appears to be compiled always for the current platform, even though I thought it would pick it from toolchain definition) and I'm not sure how.

**Comment by podtserkovskiy** [comment]
> This issue is a bit old and the `system_go_toolchain` was published, but I'm curious how this can be used to do cross compilation of the Go binary.
> 
> I was trying to create toolchain similar to `system_go_toolchain` where I hardcoded `env_go_os` and `env_go_arch`, but I still need to provide stdlib which is compiled for that platform (it's using the default one which appears to be compiled always for the current platform, even though I thought it would pick it from toolchain definition) and I'm not sure how.

@dankox setting env_go_os and env_go_arch should be enough for cross-compilation, there's no need to supply stdlib anymore, we build it on-demand. If you still see it in GoToolchainInfo please upgrade buck2/buck2-prelude.

**Comment by dankox** [comment]
> @dankox setting env_go_os and env_go_arch should be enough for cross-compilation, there's no need to supply stdlib anymore, we build it on-demand. If you still see it in GoToolchainInfo please upgrade buck2/buck2-prelude.
> 
> If something doesn't work I'm here and happy to help 😀

@podtserkovskiy Hey, thanks for coming back to me for this issue:) I'm still having a problem and I have the latest prelude. I could configure the `env_go_os` and `env_go_arch` but the stdlib is causing troubles anyway.

I have pushed my setup here (it's really simple one file project where I was trying it first):
https://github.com/dankox/colorx/tree/buck2-test                      

I'm not sure if I'm using it correctly, but it seems that the build of the `main.go` works fine, until it tries to import `fmt` package which was build for another platform. I thought it might be caused by me building first the binary for my platform and later trying to cross-compile, but even if I remove everything and go for other platform, I will get this error:
```
Connected to new buck2 daemon.
Action failed: root//:colorx_linux (go_compile main)
Local command returned non-zero exit code 1
Reproduce locally: `env -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/root/ca7581441d28fa24/go_compile/main' 'GOARCH=amd64' 'GOE ...<omitted>... g -o buck-out/v2/gen/root/3a2dd161323a3ea9/__colorx_linux__/__action__4__/go_compile_out.a ./main.go (run `buck2 log what-failed` to get the full command)`
stdout:
./main.go:4:2: could not import fmt (object is [go object darwin amd64 go1.22.2 GOAMD64=v1 X:regabiwrappers,regabiargs,allocheaders,exectracer2
] expected [go object linux amd64 go1.22.2 GOAMD64=v1 X:regabiwrappers,regabiargs,allocheaders,exectracer2
])
stderr:
Build ID: 899d8947-949a-4091-a477-bb48bb370f2f
Jobs completed: 75. Time elapsed: 20.8s.
Cache hits: 0%. Commands: 6 (cached: 0, remote: 0, local: 6)
BUILD FAILED
```

**Comment by podtserkovskiy** [comment]
I'm sorry for missing the notification, thank you for creating [the repro](https://github.com/dankox/colorx/tree/buck2-test).
I'll debug it shortly.

**Comment by podtserkovskiy** [comment]
I've done a PR https://github.com/dankox/colorx/pull/1/files
I did a few changes:
- added platforms for different combinations os/arch
- added `select()` on `toolchains//:go`
- removed prelude submodule and added bundled prelude (that's the current recommended way)
- removed go_linux toolchain and colorx_linux binary

To do a cross-platform build you need to specify `--target-platforms` flag with a specific platform
For example for darwin/amd64 your build command will look like this
```
buck2 build --target-platforms root//platforms:macos_x86_64 root//:colorx
```

Roughly `target-platforms` sets `constraint_values `, then `select()` on `toolchains//:go` maps this on go-specific target platform options.

You can't override `_go_toolchain` because other dependencies like go_stdlib will still use `toolchains//:go`

You must define your own `toolchains//:go` instead.

BTW, I'll add [these selects](https://github.com/podtserkovskiy/colorx/commit/9e25014b558951be5b6b31ea777caefcce171ec0#diff-5853acbe252d617d4b790c6427dab3818a8484d19e31b7e53b6643a79cb01bcdR20-R27) to `system_go_toolchain` to make it cross-compile.

**Comment by dankox** [comment]
@podtserkovskiy Thanks a lot for that PR and the explanation. It really helps a lot. Now it makes much more sense to me, so thank you:)

**Comment by alexlian** [comment]
Per comments, looks resolved and answered. Will close, though feel free to re-open or create a new issue as needed.

**Comment by podtserkovskiy** [comment]
We've open-sourced a hermetic Go Toolchain, see examples [here](https://github.com/facebook/buck2/blob/main/examples/toolchains/go_toolchain/toolchains/BUCK)
